name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# 添加权限设置
permissions:
  contents: read
  pages: write
  id-token: write

# 允许并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          echo "Dependencies installed successfully"
        
      - name: Build uni-app for H5
        run: |
          echo "Building uni-app for H5..."
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          # 设置更宽松的内存限制
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build:h5
          echo "Build completed successfully"
        env:
          NODE_ENV: production
          CI: true
          
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ -d "./dist/build/h5" ]; then
            echo "Build directory exists"
            ls -la ./dist/build/h5/
            if [ -f "./dist/build/h5/index.html" ]; then
              echo "index.html found - deployment ready"
            else
              echo "No index.html found, creating fallback"
              cp test-deploy.html ./dist/build/h5/index.html
            fi
          else
            echo "Creating fallback deployment structure"
            mkdir -p ./dist/build/h5
            cp test-deploy.html ./dist/build/h5/index.html
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/build/h5'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4