name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# 添加权限设置
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build:h5
      env:
        VITE_QIANWEN_API_KEY: ${{ secrets.VITE_QIANWEN_API_KEY }}
        
    - name: Check build output
      run: |
        echo "Checking build output..."
        ls -la ./dist/build/h5/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/build/h5
        force_orphan: true